### ISSUE TITLE
How long did extending CSmith take?

### ISSUE THREAD

**Issue by ChrisCummins** [ChrisLidbury/CLSmith#12]
I'm writing up a project on OpenCL testing, and am wondering if you could provide for me an estimate of the amount of development time it took to extend CSmith for OpenCL. Looking through the version history it looks like the bulk of the work was completed in Jan-Oct 2014, but I figured it's worth asking the authors directly :)

**Comment by 0152la** [comment]
I think your estimate is good enough. I believe I joined the project around June, at which point Chris had already put a fair amount of work into it. Most of the work was finished around October - November, then I believe we did further evaluation and a bit of bug fixing through December, maybe January.

**Comment by ChrisCummins** [comment]
Thanks :)
